 (19 sloc)  469 Bytes
# Validate with curl --data-binary @.codecov.yml https://codecov.io/validate
codecov:
  archive:
    uploads: no

coverage:
  precision: 2
  round: down
  range: 90...100
  status:
    project:
      default:
        # coverage may fall by <1.0% and still be considered "passing"
        threshold: 1.0%
    patch:
      default:
        # coverage may fall by <1.0% and still be considered "passing"
        threshold: 1.0%

comment:
  layout: "header, diff, changes"
© 2019 GitHub, Inc.